services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: imersao17
    ports:
      - 3307:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
